alter table MY_MESSENGER_MESSAGE add constraint FK_MY_MESSENGER_MESSAGE_ON_USER_SENDER foreign key (USER_SENDER_ID) references SEC_USER(ID);
alter table MY_MESSENGER_MESSAGE add constraint FK_MY_MESSENGER_MESSAGE_ON_USER_RECIPIENT foreign key (USER_RECIPIENT_ID) references SEC_USER(ID);
create index IDX_MY_MESSENGER_MESSAGE_ON_USER_SENDER on MY_MESSENGER_MESSAGE (USER_SENDER_ID);
create index IDX_MY_MESSENGER_MESSAGE_ON_USER_RECIPIENT on MY_MESSENGER_MESSAGE (USER_RECIPIENT_ID);
